image: nojaf/fable-azure-functions:1.0
ports:
  - port: 8080
    onOpen: ignore
  - port: 9090
    onOpen: ignore
tasks:
  - init: dotnet tool restore && dotnet fake run build.fsx -t InstallClient -p 2
vscode:
  extensions:
    - ms-dotnettools.csharp
    - ionide.ionide-fsharp
